# ps-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ps-app-deployment
spec:
  selector:
    matchLabels:
      app: ps-app
  template:
    metadata:
      labels:
        app: ps-app
    spec:
      containers:
        - name: ps-app-container
          image: us-central1-docker.pkg.dev/pluralsight-demos-475513/ps-registry/pluralsight-app:13
          ports:
            - containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STARTUP_DELAY_SECONDS
              value: '1'
          
          resources:
            requests:
              cpu: "500m"

          startupProbe:
            httpGet:
              path: /health/startup
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 2
            failureThreshold: 15
          
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 1
          
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 1 
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ps-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ps-app-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50           
---
apiVersion: v1
kind: Service
metadata:
  name: ps-app-service
spec:
  selector:
    app: ps-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

