apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ps-app.yaml

images:
- name: us-central1-docker.pkg.dev/pluralsight-demos-475513/ps-registry/pluralsight-app
  newTag: 749e9e9
